### ISSUE TITLE
wrong year in projection text

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [chantelwetzel-noaa/dover_sole_2021#1]
@chantelwetzel-noaa I was pirating text from you and noticed that a year is wrong in the executive summary 2023 should be 2022 for `likely higher than what the true removals may be in 2021 and 2023`.

https://github.com/chantelwetzel-noaa/dover_sole_2021/blob/6b8c0549f35bebbf8c7da34765ed40f0492cbf04/write_up/01executive.Rmd#L184

**Comment by chantelwetzel-noaa** [comment]
Thank you Mrs. Pirate.
